# Intentionally incomplete App Engine template.
# Students must adapt runtime settings, entrypoint, env vars,
# and service integration for their own deployment.

runtime: python311

entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker main:app
beta_settings:
  cloud_sql_instances: "previo-2-nube:us-central1:previo-nube-bd"
  
env_variables:
  # TODO: Fill these values for your project setup.
  GOOGLE_CLOUD_PROJECT: "previo-2-nube"
  DB_HOST: "/cloudsql/previo-2-nube:us-central1:previo-nube-bd"
  DB_NAME: "cloudstore"
  DB_USER: "postgres"
  DB_PASSWORD: "TrioDinamico"
  GCS_BUCKET_NAME: "bucket-previo2-nube"
  FIRESTORE_COLLECTION_AUDIT_EVENTS: "audit_events"
  
